alias home="cd ~"
alias k=kubectl
alias ks=kubens
alias s="source ~/.profile"
alias cdtf='cdtfswitch'
alias cdtg='cdtgswitch'
alias tf='terraform'
alias tg='terragrunt'
alias diskusage='df -h'
alias folderusage='du -ch'
alias totalfolderusage='du -sh'
alias mcc='mc'
alias creds="aws-vault exec \$AWS_PROFILE"
alias zs="source ~/.zshrc"
alias nomore='find ./ -iname .DS_Store -delete'
alias clearzshhist='echo "" > ~/.zsh_history & exec \$SHELL -l'
alias clearbashhist='echo "" > ~/.bash_history & exec \$SHELL -l'
alias k=kubectl
alias ks=kubens
alias kd=kubedecode
alias kx=kubectx
alias brewup='brew update && brew upgrade && brew cleanup'
alias ugen='uuidgen | tr "[:upper:]" "[:upper:]"'
alias diskusage="df -h"
alias folderusage="du -ch"
alias totalfolderusage="du -sh"
alias sshl="ssh-add -l -E md5"
