name: validator

on: [push, pull_request, issues]

jobs:
  docs:
    name: pre commit hook
    runs-on: macOS-latest
    if: "contains(github.event.head_commit.message, 'validate') || contains(github.event.head_commit.message, 'release')"
    steps:
    - uses: actions/checkout@master
      with:
      fetch-depth: '1'

    - name: Install Deps
      run: |
        brew install pre-commit
    - name: Check All Files
      run: |
        pre-commit run --all-files
